Updated test workflow actions

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -10,23 +10,38 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Log in to Docker Hub
-      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+      - name: Check Train Workflow Conclusion
+        id: check_train_conclusion
+        uses: actions/github-script@v5
+        with:
+          script: |
+            const conclusion = '${{ github.event.workflow_run.conclusion }}';
+            console.log(`Train workflow conclusion: ${conclusion}`);
+            return conclusion;
 
-    - name: Pull Docker image
-      run: docker pull bhandar1994/myapp:${{ github.sha }}
+      - name: Fail if Train Workflow Failed
+        if: steps.check_train_conclusion.outputs.result != 'success'
+        run: exit 1
 
-    - name: Pull and Run Docker Image
-      run: |
-        score=$(docker run --rm bhandar1994/myapp:${{ github.sha }})
-        if (( $(echo "$score > 0.25" | bc -l) )); then
-          echo "Test passed"
-        else
-          echo "Test failed"
-          exit 1
-        fi
+      - name: Log in to Docker Hub
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+
+      - name: Pull Docker image
+        run: docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
+
+      - name: Testing this step
+        run: echo "The pull is success!"
+
+      - name: Pull and Run the Docker Image 
+        run: |
+          score=$(docker run --rm ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }})
+          if (( $(echo "$score > 0.50" | bc -l) )); then
+            echo "Test passed"
+          else
+            echo "Test failed"
+            exit 1
+          fi
