testing the fail-both branch

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -5,24 +5,46 @@ on:
     workflows: ["Train"]
     types:
       - completed
-      - requested
+
+env:
+  IMAGE_NAME: ai-mlops-assignment
+  REGISTRY: docker.io
+  VERSION: 1.0
 
 jobs:
   test:
     runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Pull and Run Docker Image
-      run: |
-        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
-        docker pull Shridharbhandar/Shridhar_CI_CD_AIMLOps
-        score=$(docker run --rm Shridharbhandar/Shridhar_CI_CD_AIMLOps)
-        if (( $(echo "$score > 0.50" | bc -l) )); then
-          echo "Test passed"
-        else
-          echo "Test failed"
-          exit 1
-        fi
+      - name: Check Train Workflow Conclusion
+        id: check_train_conclusion
+        uses: actions/github-script@v5
+        with:
+          script: |
+            const conclusion = '${{ github.event.workflow_run.conclusion }}';
+            console.log(`Train workflow conclusion: ${conclusion}`);
+            return conclusion;
+
+      - name: Log in to Docker Hub
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+
+      - name: Testing this step
+        run: echo "The Login is success!!!"
+
+      - name: Pull Docker image
+        run: docker pull ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}
+
+      - name: Testing this step
+        run: echo "The pull is success!!!"
+
+      - name: Pull and Run the Docker Image 
+        run: |
+          score=$(docker run --rm  ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION})
+          if (( $(echo "$score > 0.40" | bc -l) )); then
+            echo "Test passed"
+          else
+            echo "Test failed"
+            exit 1
+          fi
