Additional condition for train workflow status

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -24,10 +24,10 @@ jobs:
             return conclusion;
 
       - name: Fail if Train Workflow Failed
-        if: >
-          ${{ steps.check_train_conclusion.outputs.result != 'success' }}
-        run: exit 1
-          
+        if: steps.check_train_conclusion.outputs.result != 'success'
+        run: |
+          echo "Train workflow failed or produced a non-successful conclusion."
+          exit 1
 
       - name: Log in to Docker Hub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
