Updated with Registry details

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -5,7 +5,12 @@ on:
     workflows: ["Train"]
     types:
       - completed
-      - requested
+      #- requested
+
+env:
+  IMAGE_NAME: ai-mlops-assignment
+  REGISTRY: docker.io
+  VERSION: 1.0
 
 jobs:
   test:
@@ -14,18 +19,36 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Check Train Workflow Conclusion
+        id: check_train_conclusion
+        uses: actions/github-script@v5
+        with:
+          script: |
+            const conclusion = '${{ github.event.workflow_run.conclusion }}';
+            console.log(`Train workflow conclusion: ${conclusion}`);
+            return conclusion;
+
+      - name: Fail if Train Workflow Failed
+        if: steps.check_train_conclusion.outputs.result != 'success'
+        run: |
+          echo "Train workflow failed or produced a non-successful conclusion."
+          exit 1
+
       - name: Log in to Docker Hub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
+      - name: Testing this step
+        run: echo "The Login is success!!!"
+
       - name: Pull Docker image
-        run: docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
+        run: docker pull ${IMAGE_NAME} ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}
 
       - name: Testing this step
-        run: echo "The pull is success!"
+        run: echo "The pull is success!!!"
 
       - name: Pull and Run the Docker Image 
         run: |
-          score=$(docker run --rm ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }})
+          score=$(docker run --rm ${IMAGE_NAME} ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}
           if (( $(echo "$score > 0.50" | bc -l) )); then
             echo "Test passed"
           else
