Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,9 +1,10 @@
-name: Train
+name: Test
 
-on:
-  pull_request:
-    branches: 
-      - '*'
+on: 
+  workflow_run:
+    workflows: ["Train"]
+    types:
+      - completed
 
 env:
   IMAGE_NAME: ai-mlops-assignment
@@ -11,20 +12,40 @@ env:
   VERSION: 1.0
 
 jobs:
-  build:
+  test:
+    if: github.event.workflow_run.conclusion == 'success'
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Login to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Check Train Workflow Conclusion
+        id: check_train_conclusion
+        uses: actions/github-script@v5
+        with:
+          script: |
+            const conclusion = '${{ github.event.workflow_run.conclusion }}';
+            console.log(`Train workflow conclusion: ${conclusion}`);
+            return conclusion;
 
-    - name: Build and Push Docker Image
-      run: |
-        docker build -t ${IMAGE_NAME} .
-        docker tag ${IMAGE_NAME} ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}
-        docker push ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}
+      - name: Log in to Docker Hub
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+
+      - name: Testing this step
+        run: echo "The Login is success!!!"
+
+      - name: Pull Docker image
+        run: docker pull ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}
+
+      - name: Testing this step
+        run: echo "The pull is success!!!"
+
+      - name: Pull and Run the Docker Image 
+        run: |
+          score=$(docker run --rm  ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION})
+          if (( $(echo "$score > 0.40" | bc -l) )); then
+            echo "Test passed"
+          else
+            echo "Test failed"
+            exit 1
+          fi
